// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP5gSFWa-XYFBhMxFbOcyjwzSycB52suE',
    appId: '1:384967649765:web:abcdef',
    messagingSenderId: '384967649765',
    projectId: 'robot-delivery-cbdcf',
    authDomain: 'robot-delivery-cbdcf.firebaseapp.com',
    databaseURL: 'https://robot-delivery-cbdcf-default-rtdb.firebaseio.com',
    storageBucket: 'robot-delivery-cbdcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP5gSFWa-XYFBhMxFbOcyjwzSycB52suE',
    appId: '1:384967649765:android:01d4e46cddc9d7defc270c',
    messagingSenderId: '384967649765',
    projectId: 'robot-delivery-cbdcf',
    databaseURL: 'https://robot-delivery-cbdcf-default-rtdb.firebaseio.com',
    storageBucket: 'robot-delivery-cbdcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP5gSFWa-XYFBhMxFbOcyjwzSycB52suE',
    appId: '1:384967649765:ios:abcdef',
    messagingSenderId: '384967649765',
    projectId: 'robot-delivery-cbdcf',
    databaseURL: 'https://robot-delivery-cbdcf-default-rtdb.firebaseio.com',
    storageBucket: 'robot-delivery-cbdcf.firebasestorage.app',
    iosClientId: '384967649765-abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.example.robotDelivery',
  );
}
